### ISSUE TITLE
Problems with Wheels on M1 Apple Silicon

### ISSUE THREAD

**Issue by william-silversmith** [seung-lab/pyspng-seunglab#3]
Ran into the following error on Apple Silicon:

```
>>> import pyspng
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/wms/miniforge3/envs/tmppyspng/lib/python3.8/site-packages/pyspng/__init__.py", line 3, in <module>
    import _pyspng_c as c
ImportError: dlopen(/Users/wms/miniforge3/envs/tmppyspng/lib/python3.8/site-packages/_pyspng_c.cpython-38-darwin.so, 0x0002): symbol not found in flat namespace '_spng_ctx_free'
```

- on py39 for pip+virtualenv (yanked this wheel)
- on py38,39,310 for conda

**Comment by william-silversmith** [comment]
This is due to a failure to generate and properly integrate a universal statically compiled library binary for libspng. 

https://developer.apple.com/documentation/apple-silicon/building-a-universal-macos-binary

I deleted the universal2 wheels from PyPI as compiling from source will be potentially more reliable for M1 users that don't download the x86 binary.

**Comment by william-silversmith** [comment]
Here was an interesting experiment I did to figure out how to package a static library
[expt.tar.gz](https://github.com/seung-lab/pyspng-seunglab/files/9248011/expt.tar.gz)
.

**Comment by william-silversmith** [comment]
Hopefully solved in the latest release.
